[pytest]
addopts = -ra
testpaths = tests
filterwarnings =
    once::Warning
    ignore:::pympler[.*]


[gh-actions]
python =
    3.10: py310, lint
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314, docs


[tox]
envlist =
       lint
       {py310,py311,py312}-django4.2-drf3.16
       {py310,py311,py312,py313,py314}-django5.2-drf3.16
       docs
isolated_build = True


[testenv]
commands = pytest {posargs}
deps =
       django4.2: django==4.2.*
       django5.2: django==5.2.*
       drf3.16: djangorestframework==3.16.*
       pytest-django


[testenv:lint]
basepython = python3.10
extras = dev
passenv = HOMEPATH  # needed on Windows
commands = pre-commit run --all-files


[testenv:docs]
basepython = python3.14
extras = docs
commands = mkdocs build
